name: Validate models

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        working-directory: card_game
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Init database
        working-directory: card_game
        run: python db_init.py
